[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
contracts = {}
engine = 'chc'
timeout = 10000
targets = ['assert', 'outOfBounds', 'overflow', 'underflow', 'divByZero']

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
