[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer_runs = 0

[profile.local.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[profile.default.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[profile.production.deployer]
type = "safe"
safe = "0x32CB58b145d3f7e28c45cE4B2Cc31fa94248b23F"
propose = { type = "ledger", derivation_path = "${PROD_PROPOSER_DERIVATION_PATH}" }

[profile.staging.deployer]
type = "safe"
safe = "0x32CB58b145d3f7e28c45cE4B2Cc31fa94248b23F"
propose = { type = "ledger", derivation_path = "${STAGING_PROPOSER_DERIVATION_PATH}" }

[profile.test.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[rpc_endpoints]
celo-alfajores = "https://alfajores-forno.celo-testnet.org"
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-rpc.com"
celo = "https://forno.celo.org"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
local = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_MAIN_API_KEY}" }
celo-alfajores = { key = "${CELOSCAN_API_KEY}", chain = 44787 }
celo = { key = "${CELOSCAN_API_KEY}", chain = "celo" }
