name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: TEST
    timeout-minutes: 15
    env:  # These will be available to all steps in this job
      CELOSCAN_API_KEY: ${{ secrets.CELOSCAN_API_KEY }}
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.6'
        
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: stable
        
    - name: Install dependencies
      run: |
        # Install abigen for ABI bindings
        go install github.com/ethereum/go-ethereum/cmd/abigen@latest
        # Install jq for JSON processing
        sudo apt-get update && sudo apt-get install -y jq
        
    - name: Run integration tests
      run: make integration-test
      
  integration-tests-macos:
    name: Integration Tests (macOS)
    runs-on: macos-latest
    environment: TEST
    timeout-minutes: 15
    env:  # These will be available to all steps in this job
      CELOSCAN_API_KEY: ${{ secrets.CELOSCAN_API_KEY }}
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.6'
        
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: stable
        
    - name: Install dependencies
      run: |
        # Install abigen for ABI bindings
        go install github.com/ethereum/go-ethereum/cmd/abigen@latest
        # Install jq (macOS has it by default via Xcode Command Line Tools)
        if ! command -v jq &> /dev/null; then
          brew install jq
        fi
        
    - name: Run integration tests
      run: make integration-test
      
