name: Validate ABI Bindings

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'treb-sol/**'
      - 'cli/pkg/abi/**'
      - 'Makefile'

permissions:
  contents: read

jobs:
  validate-bindings:
    name: Validate ABI Bindings
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      
      - name: Install abigen
        run: |
          go install github.com/ethereum/go-ethereum/cmd/abigen@latest
      
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Update treb-sol submodule to latest
        run: |
          git submodule update --remote treb-sol
      
      - name: Generate ABI bindings
        run: |
          make bindings
      
      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain cli/pkg/abi/) ]]; then
            echo "❌ ABI bindings are not up to date with treb-sol changes"
            echo "🔧 Please run 'make bindings' and commit the updated bindings"
            echo ""
            echo "Changed files:"
            git status --porcelain cli/pkg/abi/
            echo ""
            echo "Diff:"
            git diff cli/pkg/abi/
            exit 1
          else
            echo "✅ ABI bindings are up to date"
          fi
      
      - name: Verify build works with updated bindings
        run: |
          make build
      
      - name: Run tests
        run: |
          go test -v ./...